name: 'Deploy Docker Image to Heroku App'
author: 'Jean Carlos Taveras'
description: 'A simple action to build, push and deploy a Docker Image to your Heroku app.'
branding:
  icon: package
  color: purple
runs:
  using: 'node12'
  main: 'dist/index.js'
